name: Lives
version: '${project.version}'
main: me.bubbles.lives.Lives
api-version: 1.19
commands:
  lively:
    command: /<command>
    description: Base command for lives plugin
  lives:
    command: /<command>
    description: Alias for /lively lives